Expose aruco detection parameters and tweak some values
UbiquityRobotics/fiducials pull request #54
Opened 2017-01-29 21:23 UTC by jim-v

Another step towards addressing #2

2017-01-30 02:23 UTC, rohbotics approved these changes
Looks good, we should make these dynamic reconfigurable to make tuning easier.

2017-01-31 23:37 UTC, jim2v commented
Yes, good idea, @rohbotics .  Can you take a look, please.

2017-02-01 16:27 UTC, rohbotics requested changes

2017-02-01 16:27 UTC, rohbotics commented on aruco_detect/src/aruco_detect.cpp
> -
Keep the parameter versions, otherwise we can't load these settings from a yaml file.

2017-02-02 06:21 UTC, rohbotics approved these changes
Looks good, thanks!

2017-02-02 07:32 UTC, merged