Multi fiducial estimation
UbiquityRobotics/fiducials pull request #87
Opened 2017-07-02 23:47 UTC by jim-v

Can estimate camera pose from all visible vertices with a single call to cv::solvePnP().
This required moving pose estimation to the fiducial_slam, since that is where the map resides
To turn the new feature on, do_pose_estimation should be false for aruco_detect, true for fiducial_slam.
By default, it's off, for now.

Closes #63.

2017-07-17 14:53 UTC, rohbotics requested changes

2017-07-17 14:53 UTC, rohbotics commented on aruco_detect/src/aruco_detect.cpp
> +        if (doPoseEstimation) {
Good, making this configurable is definitely the right choice for now.

2017-07-17 14:53 UTC, rohbotics commented on fiducial_slam/include/fiducial_slam/estimate.h
> +class Estimation {
Nitpick: This should be estimator. Estimation sounds like a class that stores a single estimate

2017-07-18 01:25 UTC, jim-v commented
Thanks for the review, @rohbotics.  The latest commit addresses your comments.

2017-07-20 02:42 UTC, rohbotics approved these changes

2017-07-20 04:36 UTC, merged